# Generated by Django 4.1.7 on 2023-03-09 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cuntuct_us_education_experience_portfolio_services_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuntuct_us',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Cuntuct_us'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Education'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Experience'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Portfolio'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'ordering': ['-id'], 'verbose_name_plural': 'UserInfo'},
        ),
        migrations.RemoveField(
            model_name='userinfotranslation',
            name='experince',
        ),
    ]
