# Generated by Django 4.1.7 on 2023-05-14 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cuntuct_us_user_education_user_experience_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='posttranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='posttranslation',
            name='master',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostTranslation',
        ),
    ]
