# Generated by Django 4.1.7 on 2023-11-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_services_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
